### ISSUE TITLE
Safes without plotpoles

### ISSUE THREAD

**Issue by karrosher** [ZzBombardierzZ/Professionals_Playground_Epoch_Issue_Tracking#13]
- Potential implementation of a new feature that will delete safes/lockboxes that are not associated to a plot after a restart has occured. Therefore removing storage that bypasses the base/plot pole limitation. 

- A warning notification to be added upon removal of the plotpole to notify a player of the risk beforehand. 

- 'Safes and storage containers are deleted next restart if not under a plotpole. You have been warned'

**Comment by Bulkpowder** [comment]
In my personal opinion, one restart would be kinda rough for players moving bases or whatever. Maybe 24h would be better?

**Comment by ZzBombardierzZ** [comment]
@Bulkpowder That's valid. It could be 10-20% damage applied each restart that there's no plot. Alternatively, people who are trying to move bases could simply ask for admin help. We can keep thinking of alternatives as well.

**Comment by ZzBombardierzZ** [comment]
I will still add a warning notification when removing plots, saying "objects without a plot pole may be deleted by an admin or automatically via script", but won't set up any automatic removal yet while we can come up with a good plan for this.
