### ISSUE TITLE
Remote door autolock

### ISSUE THREAD

**Issue by karrosher** [ZzBombardierzZ/Professionals_Playground_Epoch_Issue_Tracking#23]
Change to remote door feature to autolock doors upon closing.

**Comment by ZzBombardierzZ** [comment]
Needs testing to confirm that this is an issue.

As mentioned in discord - "if someone opens it with manual but remote closes it dosent lock"

**Comment by ZzBombardierzZ** [comment]
Metal drawbridge doesn't even open/unlock at all - this is a bug with default Epoch garage door opener.

**Comment by ZzBombardierzZ** [comment]
Confirmed both parts of this issue. New fixed behavior is to leave locked if opening remotely, but makes sure the door gets locked when closing remotely. Additionally, fixed metal drawbridges not working with remote opener.
