### ISSUE TITLE
Joining Test Server Crashes on First Attempt

### ISSUE THREAD

**Issue by fur-dozy** [ZzBombardierzZ/Professionals_Playground_Epoch_Issue_Tracking#53]
When joining the test server, the first attempt will normally crash the game. On further attempts, the connection is successful.

Steps to reproduce:
-Load the game from either DZ launcher or the in game server browser.
-After connecting, attempt to load into the game.
-Once the "setup completed" stage is reached, the game usually crashes.

**Comment by ZzBombardierzZ** [comment]
Thanks for reporting but this is actually a known issue I've seen on several servers, including the main PPG server. HeadlessClient helps resolve this, but the first player to join a server has a ~50% chance to crash. No known fix, I've tried a bunch of different solutions on a friend's server, bot is the only real workaround we've found.
