### ISSUE TITLE
Add Discord Admin Message

### ISSUE THREAD

**Issue by fur-dozy** [ZzBombardierzZ/Professionals_Playground_Epoch_Issue_Tracking#57]
When a player in the server mentions "discord", the server should show a message to that player including the discord url.

**Comment by ZzBombardierzZ** [comment]
Discord link is able to be copied and pasted from Player Menu but sure, I can add an auto message as well.

**Comment by ZzBombardierzZ** [comment]
When player message contains "discord" and "?" an admin message will dm the player saying "Looking for the discord server? You can find the discord information in the Player menu by pressing Tab | F8 | Right-Alt, which can be highlighted and then copied/pasted."
